-- 코드를 입력하세요
SELECT
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM
    BOOK AS b
LEFT JOIN 
    AUTHOR AS a
    ON b.AUTHOR_ID = a.AUTHOR_ID
LEFT JOIN
    BOOK_SALES AS bs
    ON b.BOOK_ID = bs.BOOK_ID
WHERE
    DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY 
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY
ORDER BY
    AUTHOR_ID,
    CATEGORY DESC