-- 코드를 입력하세요
SELECT DISTINCT t1.USER_ID, t1.PRODUCT_ID
FROM ONLINE_SALE as t1
JOIN ONLINE_SALE as t2
  ON t1.USER_ID = t2.USER_ID
  AND t1.PRODUCT_ID = t2.PRODUCT_ID
  AND t1.ONLINE_SALE_ID <> t2.ONLINE_SALE_ID
ORDER BY t1.USER_ID ASC, t1.PRODUCT_ID DESC;
