-- 코드를 입력하세요
SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    GENDER,
    COUNT(DISTINCT t1.USER_ID) AS USERS
FROM 
    USER_INFO t1
JOIN 
    ONLINE_SALE t2
ON 
    t1.USER_ID = t2.USER_ID
WHERE 
    GENDER IS NOT NULL
GROUP BY 
    YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY
    YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
    