-- 코드를 입력하세요
SELECT t1.CAR_ID, IF(t2.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY t1
    LEFT JOIN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE
    ) AS t2
    ON t1.CAR_ID = t2.CAR_ID
GROUP BY t1.CAR_ID
ORDER BY t1.CAR_ID DESC

