-- 코드를 입력하세요
SELECT 
    t1.PRODUCT_ID, 
    PRODUCT_NAME, 
    SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM 
    FOOD_PRODUCT t1
JOIN 
    FOOD_ORDER t2
ON 
    t1.PRODUCT_ID = t2.PRODUCT_ID	
WHERE 
    YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5	
GROUP BY 
    t1.PRODUCT_ID
ORDER BY 
    TOTAL_SALES DESC, t1.PRODUCT_ID