-- 코드를 작성해주세요
SELECT 
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    (m.max_size - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM 
    ECOLI_DATA e
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS max_size
    FROM 
        ECOLI_DATA
    GROUP BY 
        YEAR(DIFFERENTIATION_DATE)
) m ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY 
    YEAR ASC,
    YEAR_DEV ASC;