-- 코드를 입력하세요
SELECT
    DISTINCT t1.CAR_ID
FROM 
    CAR_RENTAL_COMPANY_CAR t1
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY t2
ON 
    t1.CAR_ID = t2.CAR_ID
WHERE 
    CAR_TYPE = '세단' AND START_DATE > '2022-09-30'
ORDER BY 
    t1.CAR_ID DESC