-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO t1
JOIN FISH_NAME_INFO t2
ON t1.FISH_TYPE = t2.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH 
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) t3
ON t1.FISH_TYPE = t3.FISH_TYPE
AND t1.LENGTH = t3.MAX_LENGTH;