-- 코드를 입력하세요
SELECT TITLE, t1.BOARD_ID, t2.REPLY_ID, t2.WRITER_ID, t2.CONTENTS, DATE_FORMAT(t2.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD as t1
JOIN USED_GOODS_REPLY as t2
ON t1.BOARD_ID = t2.BOARD_ID
WHERE YEAR(t1.CREATED_DATE) = 2022 AND MONTH(t1.CREATED_DATE) = 10
ORDER BY t2.CREATED_DATE ASC, t1.TITLE ASC