-- 코드를 작성해주세요
SELECT 
    t1.DEPT_ID,
    DEPT_NAME_EN,
    ROUND(AVG(SAL), 0) AS AVG_SAL
FROM 
    HR_DEPARTMENT t1
JOIN 
    HR_EMPLOYEES t2
ON
    t1.DEPT_ID = t2.DEPT_ID
GROUP BY 
    t1.DEPT_ID, DEPT_NAME_EN
ORDER BY 
    AVG_SAL DESC