-- 코드를 입력하세요
SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM 
    BOOK t1
JOIN 
    BOOK_SALES t2
ON 
    t1.BOOK_ID = t2.BOOK_ID
WHERE 
    YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY