-- 코드를 입력하세요
SELECT p1.CATEGORY, p2.MAX_PRICE, p1.PRODUCT_NAME
FROM FOOD_PRODUCT p1
    JOIN 
    (SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY) AS p2
WHERE 
    p1.CATEGORY = p2.CATEGORY AND 
    p1.PRICE = p2.MAX_PRICE AND 
    p1.CATEGORY IN ('과자', '국', '김치', '식용유')   
ORDER BY 
    p1.PRICE DESC