-- 코드를 작성해주세요
SELECT 
    COUNT(FISH_TYPE) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM 
    (
        SELECT 
            FISH_TYPE,
            IF(LENGTH <= 10 OR LENGTH IS NULL, 10, LENGTH) AS LENGTH
        FROM FISH_INFO
    ) AS ADJUSTED_FISH
GROUP BY 
    FISH_TYPE
HAVING 
    AVG(LENGTH) >= 33
ORDER BY 
    FISH_TYPE